version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tweet_extractor
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: tweetextractor
    ports:
      - 27017:27017
    volumes: 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # tweet-extractor:
  #   image: "tweet-extractor:dev-tag"
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ../config.json:/config.json
