// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewSearchQuery struct {
	Tags   []string `json:"tags"`
	Active bool     `json:"active"`
}

type NewTalkshow struct {
	Kanal string `json:"kanal"`
	Host  string `json:"host"`
}
